name: Monthly Drawer Report

on:
  schedule:
    - cron: '0 12 1 * *'  # Runs at 12:00 UTC on the 1st of every month
  workflow_dispatch:      # Allows manual run from GitHub UI

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Monthly Report Script
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          python Backend/monthly_report.py
