# This GitHub Actions workflow automates the monthly email reporting for the ESP32 Drawer Monitoring System.
# We have used AI, specifically OpenAI's ChatGPT, to assist with refining the structure of the workflow
# and ensuring clarity in comments and documentation.
# All code complies with ITU's instructions regarding Generative AI.

name: Monthly Drawer Report

on:
  schedule:
    - cron: '0 12 1 * *'  # Monthly
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install psycopg2-binary directly (failsafe)
        run: |
          pip install psycopg2-binary

      - name: Install all project dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Monthly Report Script
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          python Backend/monthly_report.py